### ISSUE TITLE
App working fine in debug mode but throw this error in release mode check this error and SimpleWidgetProvider class as per your given example

### ISSUE THREAD

**Issue by mtzinfotech** [Abedalkareem/native_widget#4]
FATAL EXCEPTION: main
                                                                Process: com.mtz.custom_notification_sound, PID: 9267
                                                                java.lang.RuntimeException: Unable to start receiver com.mtz.custom_notification_sound.SimpleWidgetProvider: java.lang.NullPointerException: Parameter specified as non-null is null: method d6.x.y, parameter <this>
                                                                	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4384)
                                                                	at android.app.ActivityThread.access$1600(ActivityThread.java:256)
                                                                	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
                                                                	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                	at android.os.Looper.loopOnce(Looper.java:201)
                                                                	at android.os.Looper.loop(Looper.java:288)
                                                                	at android.app.ActivityThread.main(ActivityThread.java:7870)
                                                                	at java.lang.reflect.Method.invoke(Native Method)
                                                                	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method d6.x.y, parameter <this>
                                                                	at d6.x.y(Unknown Source:2)
                                                                	at d6.n.y(Unknown Source:0)
                                                                	at com.mtz.custom_notification_sound.SimpleWidgetProvider.onUpdate(Unknown Source:110)
                                                                	at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:66)
                                                                	at com.mtz.custom_notification_sound.SimpleWidgetProvider.onReceive(Unknown Source:0)
                                                                	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4375)
                                                                	at android.app.ActivityThread.access$1600(ActivityThread.java:256) 
                                                                	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102) 
                                                                	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                	at android.os.Looper.loop(Looper.java:288) 
                                                                	at android.app.ActivityThread.main(ActivityThread.java:7870) 
                                                                	at java.lang.reflect.Method.invoke(Native Method) 
                                                                	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```kotlin
class SimpleWidgetProvider : AppWidgetProvider() {

    @SuppressLint("RemoteViewLayout")
    override fun onUpdate(
        context: Context,
        appWidgetManager: AppWidgetManager,
        appWidgetIds: IntArray
    ) {
        super.onUpdate(context, appWidgetManager, appWidgetIds)

        val allTimelines = AppSharedPreferences.getTimelines(context)

        if (allTimelines.isNotEmpty()) {
            appWidgetIds.forEach { widgetId ->
                var timeline = allTimelines.firstOrNull()
                val timelineWithID = allTimelines.firstOrNull { it.id == "$widgetId" }
                if (timelineWithID != null) {
                    timeline = timelineWithID
                }
                if (timeline == null) {
                    return@forEach
                }
                val timelineData = timeline.data.sortedBy { it.date }
                val widgetToShow = timelineData.lastOrNull {
                    val currentTime = System.currentTimeMillis()
                    val widgetTime = it.date
                    return@lastOrNull widgetTime <= currentTime
                } ?: return@forEach
                val views = RemoteViews(context.packageName, R.layout.widget_layout).apply {
                    // Set the widget background.xml
                    setImageViewBitmap(
                        R.id.backgroundImageView,
                        base64ToBitmap(widgetToShow.background ?: "")
                    )

                    // Set the widget foreground
                    setImageViewBitmap(
                        R.id.foregroundImageView,
                        base64ToBitmap(widgetToShow.foreground ?: "")
                    )

                    // Open App on Widget Click
                    val pendingIntent = getActivity(
                        context,
                        MainActivity::class.java,
                        Uri.parse("${Settings.appScheme}://data?id=$widgetId")
                    )
                    setOnClickPendingIntent(R.id.container, pendingIntent)
                }
                appWidgetManager.updateAppWidget(widgetId, views)
            }
        }

    }


    override fun onReceive(context: Context?, intent: Intent?) {
        super.onReceive(context, intent)
    }

    private fun base64ToBitmap(base64: String): Bitmap {
        val decodedString = Base64.decode(base64, Base64.DEFAULT)
        return BitmapFactory.decodeByteArray(decodedString, 0, decodedString.size)
    }

    private fun <T> getActivity(
        context: Context,
        activityClass: Class<T>,
        uri: Uri? = null
    ): PendingIntent where T : Activity {
        val intent = Intent(context, activityClass)
        intent.data = uri

        var flags = PendingIntent.FLAG_UPDATE_CURRENT
        if (Build.VERSION.SDK_INT >= 23) {
            flags = flags or PendingIntent.FLAG_IMMUTABLE
        }

        return PendingIntent.getActivity(context, 0, intent, flags)
    }
}
```

**Comment by Abedalkareem** [comment]
Sorry for the late reply,

Try to disable proguard and see which methods crashing.

Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method d6.x.y, parameter
at d6.x.y(Unknown Source:2)
at d6.n.y(Unknown Source:0)
